name: CI


on:
  push:
    
  pull_request:
    
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          npm install
      - name: fixing Tsx file with airbnb eslint
        run: |
          npx eslint screens/ --ext ts,tsx
          npx eslint customs/ --ext ts,tsx
          npx eslint components/ --ext ts,tsx